### PR TITLE
Fix `SwizzleArray` broadcasting

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @willow-ahrens,

In the eager mode, I think there's an issue with `broadcast(fn, ::SwizzleArray, ::SwizzleArray)`. It complained about missing functions, but with them in place it fails when performing `copyto!`.

The `test/test_issues.jl` change reproduces the issue.

### CODE REVIEW

**Comment by willow-ahrens** [comment]
The issue here is more that the swizzle wasn't declaring a FinchStyle broadcast style. I added a definition for that.

In general, most of the "interface" overloads for `Tensor` (i.e. getindex, setindex, map, broadcast, reduce, copy), should also be defined for `SwizzleArray`, `PermissiveArray`, `OffsetArray`, etc. I think the right way forward on that is to add an abstract class like `CompiledArray` that everything can inherit from for the purposes of defining interfaces in terms of the Finch compiler.

The fixes I've added so far should be good for now though!

**Comment by willow-ahrens** [comment]
Also, I've chosen not to define `length` on Finch tensors because most of the tensors require cartesian indexing to work properly, and length tends to be used for linear indexing. If at some point we want to do a linear indexing + length PR we could add them though!

**Comment by mtsokol** [comment]
Thank you! In this version `broadcast` with `SwizzleArrays` works for me! 

I think the error comes from `copyto!(A, A_sw)` line.

**Comment by willow-ahrens** [comment]
Oops! Yeah I forgot how julia `Array` cannot be resized

**Pull request merged**
