### PR TITLE
SingleRLE level

### LINKED ISSUE #329: Single run level
This is the equivalent of the banded level, but with a run. @nullplay

### PR DESCRIPTION
**Pull request by nullplay**
fixes #329

### CODE REVIEW

**Comment by willow-ahrens** [comment]
What happens if you try to write two runs to the single run level?

**Comment by nullplay** [comment]
> What happens if you try to write two runs to the single run level?

It emits an error when thawed ptr is filled. https://github.com/willow-ahrens/Finch.jl/blob/018d4fb77e5c6da07c1af7bb7fb25c5c5c128a14/src/tensors/levels/singlerlelevels.jl#L310-L311

**Comment by willow-ahrens** [comment]
is it a good error?

**Comment by willow-ahrens** [comment]
sounds great! I'll try this out when I get the chance.

**Comment by willow-ahrens** [comment]
I'm working on level docs, so I may ask you to add some docs for this once I'm done.

**Comment by nullplay** [comment]
> I'm working on level docs, so I may ask you to add some docs for this once I'm done.

Sure!

**Comment by willow-ahrens** [comment]
Once #375 merges with new documentation for levels, could you add the docs for this level in there?

**Review by willow-ahrens — COMMENTED** [review]
Once https://github.com/willow-ahrens/Finch.jl/pull/375 merges with new documentation for levels, could you add the docs for this level in there? Also, please add tests for this. Other than that, this looks good!

**Review by willow-ahrens — CHANGES_REQUESTED** [review]
Once https://github.com/willow-ahrens/Finch.jl/pull/375 merges with new documentation for levels, could you add the docs for this level in there? Also, please add tests for this. Other than that, this looks good!

**Comment by willow-ahrens** [comment]
sorry for the double review!

**Review by willow-ahrens — APPROVED** [review]
LGTM!

**Pull request merged**
