### PR TITLE
Wma/rename fiber

### LINKED ISSUE #301: RFC: Rename Fiber to TensorTree or just Tensor
Any thoughts?

### PR DESCRIPTION
**Pull request by willow-ahrens**
fixes #301

### CODE REVIEW

**Comment by wraith1995** [comment]
Why Tensorr?

**Comment by willow-ahrens** [comment]
Array is taken by Base Julia

**Comment by willow-ahrens** [comment]
@teo I didn't understand that you were pointing out a typo, sorry! I pushed a quick fix on main

**Comment by wraith1995** [comment]
@willow-ahrens I thought there was a purpose to the other r? Maybe Tensor was taken!

**Comment by willow-ahrens** [comment]
Haha I thought you had made a typo, but I realized after I merged that the `r` was deliberate!

**Pull request merged**
