### PR TITLE
Create a conversion function from fiber to vector-of-tuples

### PR DESCRIPTION
**Pull request by kylebd99**
Per the title.

### CODE REVIEW

**Review by kylebd99 — COMMENTED** [review]
Not sure where a test for this function might live. Let me know if there's a preferred spot for that.

**Comment by willow-ahrens** [comment]
Thanks for the PR! Summarizing our discussion today, let's convert this into documentation PR for some of the functions in https://github.com/willow-ahrens/Finch.jl/blob/main/src/interface/fsparse.jl, as well as countstored, nnz, dropdefaults, and perhaps some of the sparseArray conversions.

**Comment by willow-ahrens** [comment]
@kylebd99 I'm closing this PR as we already have the ffindnz functionality, and I'll add an issue for the documentation request. Thanks for your help with this!

**Comment by willow-ahrens** [comment]
The issue is here: https://github.com/willow-ahrens/Finch.jl/issues/228

**Pull request closed without merging**
